included:
  - CreditHub
  - CreditHubTests
  - CreditHubUITests

excluded:
  - CreditHub.xcodeproj
  - .build

line_length:
  warning: 160
  error: 220

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 450

file_length:
  warning: 400
  error: 600

cyclomatic_complexity:
  warning: 15
  error: 20

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id

disabled_rules:
  - todo
  - trailing_comma

opt_in_rules:
  - empty_count
  - closure_spacing
  - redundant_nil_coalescing
