import Foundation
import UIKit

/// Canned data returned by `MockAPIClient` so the app is fully runnable without a backend.
enum MockFixtures {
    static let user = UserDTO(
        id: "usr_1001",
        fullName: "Alex Morgan",
        email: "alex.morgan@example.com",
        phoneNumber: "+1 555-0142",
        memberSince: Date(timeIntervalSince1970: 1_580_000_000)
    )

    static let session = AuthSessionDTO(
        accessToken: "mock-access-token",
        refreshToken: "mock-refresh-token",
        expiresAt: Date().addingTimeInterval(3600),
        user: user
    )

    static let accounts: [CreditAccountDTO] = [
        CreditAccountDTO(
            id: "acct_1",
            productName: "Platinum Rewards Credit Line",
            accountNumberMasked: "•••• 4821",
            creditLimit: 15000,
            availableCredit: 9250.50,
            currentBalance: 5749.50,
            currency: "USD",
            status: "active"
        ),
        CreditAccountDTO(
            id: "acct_2",
            productName: "Small Business Credit Line",
            accountNumberMasked: "•••• 7734",
            creditLimit: 50000,
            availableCredit: 42000,
            currentBalance: 8000,
            currency: "USD",
            status: "active"
        )
    ]

    static let applications: [CreditApplicationDTO] = [
        CreditApplicationDTO(
            id: "app_1",
            productName: "Premium Travel Credit Line",
            requestedAmount: 20000,
            currency: "USD",
            status: "underReview",
            submittedAt: Date().addingTimeInterval(-86_400 * 3)
        )
    ]

    static let transactions: [TransactionDTO] = [
        TransactionDTO(id: "txn_1", accountId: "acct_1", description: "Grocery Mart", amount: 84.20, currency: "USD", date: Date().addingTimeInterval(-3600 * 5), type: "debit", category: "Groceries"),
        TransactionDTO(id: "txn_2", accountId: "acct_1", description: "Payment Received", amount: 500, currency: "USD", date: Date().addingTimeInterval(-3600 * 30), type: "credit", category: "Payment"),
        TransactionDTO(id: "txn_3", accountId: "acct_1", description: "Airline Booking", amount: 412.75, currency: "USD", date: Date().addingTimeInterval(-3600 * 50), type: "debit", category: "Travel")
    ]

    static let repaymentSchedule: [RepaymentInstallmentDTO] = [
        RepaymentInstallmentDTO(id: "rpm_1", accountId: "acct_1", dueDate: Date().addingTimeInterval(86_400 * 5), amountDue: 250, currency: "USD", status: "upcoming"),
        RepaymentInstallmentDTO(id: "rpm_2", accountId: "acct_1", dueDate: Date().addingTimeInterval(-86_400 * 25), amountDue: 250, currency: "USD", status: "paid")
    ]

    static let cards: [CardDTO] = [
        CardDTO(id: "card_1", accountId: "acct_1", lastFourDigits: "4821", network: "visa", cardType: "physical", status: "active", spendingLimit: 5000, currency: "USD"),
        CardDTO(id: "card_2", accountId: "acct_1", lastFourDigits: "9903", network: "mastercard", cardType: "virtual", status: "active", spendingLimit: 1000, currency: "USD")
    ]

    static let cardDetails = CardDetailsDTO(cardNumber: "4111 1111 1111 4821", expiryMonth: 9, expiryYear: 2028, cvv: "482")

    static let statements: [StatementDTO] = (0..<6).map { monthsAgo in
        let periodEnd = Calendar.current.date(byAdding: .month, value: -monthsAgo, to: Date()) ?? Date()
        let periodStart = Calendar.current.date(byAdding: .month, value: -1, to: periodEnd) ?? periodEnd
        return StatementDTO(
            id: "stmt_\(monthsAgo)",
            accountId: "acct_1",
            periodStart: periodStart,
            periodEnd: periodEnd,
            issuedDate: Calendar.current.date(byAdding: .day, value: 2, to: periodEnd) ?? periodEnd
        )
    }

    static let disputes: [DisputeDTO] = []

    /// Generates a valid single-page placeholder PDF via `UIGraphicsPDFRenderer` — used as the mock
    /// statement "document" payload so `StatementViewerView`'s `PDFView` has something real to render.
    static func placeholderStatementPDF(statementId: String) -> Data {
        let pageBounds = CGRect(x: 0, y: 0, width: 612, height: 792)
        let renderer = UIGraphicsPDFRenderer(bounds: pageBounds)
        return renderer.pdfData { context in
            context.beginPage()
            "CreditHub Statement".draw(
                at: CGPoint(x: 48, y: 48),
                withAttributes: [.font: UIFont.systemFont(ofSize: 20, weight: .semibold)]
            )
            "Statement ID: \(statementId)\nThis is a placeholder document generated by the mock API.".draw(
                at: CGPoint(x: 48, y: 84),
                withAttributes: [.font: UIFont.systemFont(ofSize: 12)]
            )
        }
    }
}
